// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCzqBM_UVGDl4pPHNSqgwpuewJSe-AAo',
    appId: '1:315652197249:android:9182d8bde62650105a7680',
    messagingSenderId: '315652197249',
    projectId: 'shripad-shrivallabh-new',
    authDomain: 'shripad-shrivallabh-new.firebaseapp.com',
    storageBucket: 'shripad-shrivallabh-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLCzqBM_UVGDl4pPHNSqgwpuewJSe-AAo',
    appId: '1:315652197249:android:9182d8bde62650105a7680',
    messagingSenderId: '315652197249',
    projectId: 'shripad-shrivallabh-new',
    storageBucket: 'shripad-shrivallabh-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR_m7LPe0doBnrsFkRI9Fc3qm4uFdBNRg',
    appId: '1:315652197249:ios:1cedefe0cce4d05e5a7680',
    messagingSenderId: '315652197249',
    projectId: 'shripad-shrivallabh-new',
    storageBucket: 'shripad-shrivallabh-new.appspot.com',
    iosBundleId: 'com.shripadshrivallabh.charitramrut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLCzqBM_UVGDl4pPHNSqgwpuewJSe-AAo',
    appId: '1:315652197249:android:9182d8bde62650105a7680',
    messagingSenderId: '315652197249',
    projectId: 'shripad-shrivallabh-new',
    storageBucket: 'shripad-shrivallabh-new.appspot.com',
    iosBundleId: 'com.shripadshrivallabh.charitramrut.RunnerTests',
  );
}
