// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe-aopM82NlfflAmlIlxq4clSolbQJN20',
    appId: '1:1098524233550:web:60b38f162ef7f01f1d581f',
    messagingSenderId: '1098524233550',
    projectId: 'shripad-shrivallabh',
    authDomain: 'shripad-shrivallabh.firebaseapp.com',
    storageBucket: 'shripad-shrivallabh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofm7Ze8oKZbBiGRpi1eZFee249_COtXE',
    appId: '1:1098524233550:android:15aba8a55f4b86361d581f',
    messagingSenderId: '1098524233550',
    projectId: 'shripad-shrivallabh',
    storageBucket: 'shripad-shrivallabh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCf6f78AL7_NmAjaBhl7F_M-S1tuVu9Yw',
    appId: '1:1098524233550:ios:2cec9b709ab971d51d581f',
    messagingSenderId: '1098524233550',
    projectId: 'shripad-shrivallabh',
    storageBucket: 'shripad-shrivallabh.appspot.com',
    iosBundleId: 'com.example.shripadShrivallabh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCf6f78AL7_NmAjaBhl7F_M-S1tuVu9Yw',
    appId: '1:1098524233550:ios:537c0ba1d479887a1d581f',
    messagingSenderId: '1098524233550',
    projectId: 'shripad-shrivallabh',
    storageBucket: 'shripad-shrivallabh.appspot.com',
    iosBundleId: 'com.example.shripadShrivallabh.RunnerTests',
  );
}
